# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stephen Nancekivell's Tech Blog
author: Stephen Nancekivell
description: > # this means to ignore newlines until "baseurl:"
  Stephens Tech Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.stephenn.com"
twitter_username: stephennancekiv
github_username: stephennancekivell
stackoverflow_username: 893854/stephen
linkedin_url: https://www.linkedin.com/in/stephen-nancekivell-77003039

permalink: /:categories/:year/:month/:title.html

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-21860813-8

disqus:
  shortname: blog-stephenn-com

sass:
  style: compressed