baseURL: 'https://stephenn.com'
languageCode: en-us
title: Stephen's Tech Blog
theme: PaperMod

enableRobotsTXT: true

minify:
    disableXML: true
    minifyOutput: true

defaultContentLanguage: en
hasCJKLanguage: false
paginate: 30
googleAnalytics: G-LNCP0VXVCC
#disqusShortname: your-disqus-shortname
permalinks:
  # posts: '/posts/:title/'
  posts: '/:year/:month/:title'

markup:
  highlight:
    guessSyntax: true
    # style: emacs
    style: dracula
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  disableThemeToggle: true
  showReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  enableRSS: true
  enableComments: false
  enableGoogleAnalytics: true
  showToc: true
  math: false
  hideFooter: true
  hiddenPostSummaryInHomePage: false
  homeInfoParams:
    Title: Hi there 👋

    Content: >
      - ## Indie Projects

      - [Webhook Wizard 🧙‍♂️](https://webhookwizard.com)

      - [Person App](https://personapp.co)

      - [Docker Dash](https://dockerdash.com)

      - [RealEmail](https://IsItARealEmail.com) (sold)

  socialIcons:
      - name: github
        url: "https://github.com/stephennancekivell"
      - name: twitter
        url: "https://twitter.com/hi_stephen_n"
      - name: linkedin
        url: "https://www.linkedin.com/in/stephen-nancekivell-77003039"
      - name: stackoverflow
        url: "https://stackoverflow.com/users/893854/stephen"

menu:
    main:
        - identifier: webhookwizard
          name: Webhook Wizard 🧙‍♂️
          url: https://webhookwizard.com
          weight: 10